Controllers/MovieListController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApi.Models;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.AspNetCore.SignalR;

namespace MovieApi.Controllers
{
    [Route("[controller]/[action]")]
    public class MovieListController : Controller
    {
        private readonly MovieContext _context;
        public MovieListController(MovieContext context, IHubContext<Hubs.MovieHub> hubContext)
        {
            _context = context;
        }
        public async Task<IActionResult> List(CancellationToken cancellationToken)
        {
            ViewData["movies"] = await _context.GetAllItems(cancellationToken);
            return View();
        }

        public IActionResult Delete(int id)
        {
            _context.DeleteItem(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> CreateAndUpdate(CancellationToken cancellationToken ,int id)
        {
            if(id > 0)
            {
                ViewBag.header = "Edit The Movie";
                MovieItem item = await _context.GetAnItem(cancellationToken,id);
                return View(item);            
            }
            MovieItem nullItem = new MovieItem();
            nullItem.posterSize = 0;
            ViewBag.header = "Create A Movie";
            return View(nullItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> CreateAndUpdate(CancellationToken cancellationToken ,MovieItem item)
        {
            
            if(item.posterFile == null)
            {
                item.poster = null;
            }
            else
            {
                var ms = new MemoryStream();
                item.posterFile.CopyTo(ms);
                var fileBytes = ms.ToArray();
                item.poster = fileBytes;
            }

            if(item.id > 0)
            {
               await _context.PutItem(cancellationToken,item);
            }
            else
            {
                _context.PostItem(item); 
            }
            return RedirectToAction("List");
        }
    }
}

Views/MovieList/CreateAndUpdate.cshtml
@model MovieApi.Models.MovieItem

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<html>
<body>
    <div class="row mt-5">
        <h1 class="text-center w-100" style="font-weight:Bold;">@ViewBag.header</h1>
    </div>
    <div class="container mt-5 ">
      @using(Html.BeginForm("CreateAndUpdate","MovieList",FormMethod.Post, new{enctype="multipart/form-data"}))
      {
         @Html.ValidationSummary()
         { 
             <div class="form-group row">
                <div class="col-5" >
                    <img src="data:image/jpg;base64, @Model.getPoster()" width="300" height="350" class="center" hidden=@Model.isNullImage()>
                </div>
                <div class="col-5">             
                    <div class="form-group row" hidden>
                    @Html.LabelFor(x => x.id, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.id, new {@class = "form-control"})
                        </div>
                    </div>
                    <div class="form-group row">
                    @Html.LabelFor(x => x.name,"Name:", new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.name, new {@class = "form-control", @maxlength= "20"})
                        </div>
                    </div>
                    <div class="form-group row">
                    @Html.LabelFor(x => x.year,"Year:", new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.year, new { @class = "form-control" ,@type="number"})
                        </div>
                    </div>
                    <div class="form-group row">
                    @Html.LabelFor(x => x.posterFile,"Movie Poster:" , new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.posterFile, new{ @type = "file"})
                        </div>
                    </div> 
                </div>    
            </div>       
            <button type="submit" class="btn btn-primary" style="float: right;" onclick="return confirm('Do you want to save the movie?');">Save</button>
         }
      }
    </div>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Views/MovieList/List.cshtml
@model MovieApi.Models.MovieItem

<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <br>
    <br>
    <h1 class="text-center">MOVIES</h1>
    <br>
    <link href="~/css/site.css" rel="stylesheet">
</head>
<html>
<body>
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col" >Image</th>
            <th scope="col">Movie Name</th>
            <th scope="col">Year</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
            @{
                foreach(var x in @ViewData["movies"] as List<MovieApi.Models.MovieItem>)
                {
                    <tr>
                        <td><img src="data:image/jpg;base64, @x.getPoster()" width="110" height="130" class="center"></td>  
                        <td class="text-center">@x.name</td>
                        <td class="text-center">@x.year</td>
                        <td class="text-center">
                            <a href="@Url.Action("CreateAndUpdate","MovieList", new{id=x.id})"><button type="button" class="btn btn-success"><i class="far fa-edit">Edit</button></a>  
                            <a href="@Url.Action("Delete","MovieList", new{id=x.id})" onclick="return confirm('Do you want to delete this movie?');"><button type="button" class="btn btn-danger"><i class="far fa-trash-alt">Delete</button></a>  
                        </td>
                    </tr>
                }
            }
        </tbody>
      </table>
        <a href="@Url.Action("CreateAndUpdate","MovieList", new{id= -1})"><button type="button" class="btn btn-primary" style="float: right;"><i class="far fa-trash-alt">Add a Movie</button></a>  
    </div>
  </div>
</div>


    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>